run:
  modules-download-mode: readonly
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - golint
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
linters-settings:
  errcheck:
    check-type-assertions: true
    ignore: ""
