apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment-{{.TRAVIS_BRANCH}}
  labels:
    app: hello
    branch: "{{.TRAVIS_BRANCH}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
        branch: "{{.TRAVIS_BRANCH}}"
    spec:
      containers:
        - name: the-container
          image: nginxdemos/hello:{{.ImageTag}}
          ports:
            - containerPort: 80
          env:
            - name: GREETING
              value: "{{.Greeting}}"
            - name: DB_CONNECTION_STRING
              value: "User ID=root;Host=the-test-db-server;Port=5432;Database=the-db;"
            - name: DEBUG
              value: "true"
