name: CI

on:
  push:
    tags: ["v*"]
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: go mod download
      - uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.40.1
      - run: go test ./...
      - run: ./scripts/build.sh
      - if: ${{ env.KYML_RELEASE_VERSION }}
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "v${{ env.KYML_RELEASE_VERSION }}"
          files: bin/*
